# -*- coding: utf-8 -*-

{
    'name': 'Invoice Format Editor',
    'version': '14.0.2.1.',
    'category': 'Accounting',
    'summary': 'Invoice Format Editor',
    'description': """Invoice Format Editor For Configuring the Invoice Templates""",
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'images': ['static/description/banner.png'],
    'website': 'https://www.cybrosys.com',
    'depends': ['account'],
    'data': ['security/ir.model.access.csv',
             'data/design_templates.xml',
             'views/custom_layouts.xml',
             'views/document_base_layout.xml',
             'reports/custom_invoice_template.xml',
             'reports/default_invoice_template.xml',
             'template_view/default_template_view.xml',
             'template_view/normal_template_view.xml',
             'template_view/modern_template_view.xml',
             'template_view/old_template_view.xml',
             ],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,

}
